// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function capitalize(s) {
  let len = s.length;
  if (len === 0) {
    return s;
  }
  let first = s[0].toUpperCase();
  let rest = s.slice(1);
  return first + rest;
}

function uncapitalize(s) {
  let len = s.length;
  if (len === 0) {
    return s;
  }
  let first = s[0].toLowerCase();
  let rest = s.slice(1);
  return first + rest;
}

function splitIntoWords(s) {
  let withDashes = Js_string.replaceByRe(/-/, s, " ");
  let withSpaces = Js_string.replaceByRe(/_/, withDashes, " ");
  let splitCamel = Js_string.replaceByRe(/([a-z])([A-Z])/g, withSpaces, "$1 $2");
  let splitCaps = Js_string.replaceByRe(/([A-Z]+)([A-Z][a-z])/g, splitCamel, "$1 $2");
  return Js_string.split(splitCaps, " ").filter(word => word !== "");
}

function pascalCase(s) {
  return splitIntoWords(s).map(capitalize).join("");
}

function camelCase(s) {
  let words = splitIntoWords(s);
  if (words.length === 0) {
    return s;
  }
  let first = uncapitalize(Stdlib_Option.getOrThrow(words[0], undefined));
  let rest = words.slice(1).map(capitalize).join("");
  return first + rest;
}

function kebabCase(s) {
  return splitIntoWords(s).map(prim => prim.toLowerCase()).join("-");
}

function snakeCase(s) {
  return splitIntoWords(s).map(prim => prim.toLowerCase()).join("_");
}

function upper(prim) {
  return prim.toUpperCase();
}

function lower(prim) {
  return prim.toLowerCase();
}

function trim(prim) {
  return prim.trim();
}

function title(s) {
  return Js_string.split(s, " ").map(s => capitalize(s).toLowerCase()).join(" ");
}

function makeHelpers() {
  return {
    pascalCase: pascalCase,
    camelCase: camelCase,
    kebabCase: kebabCase,
    snakeCase: snakeCase,
    upper: upper,
    lower: lower,
    trim: trim,
    title: title,
    capitalize: capitalize,
    uncapitalize: uncapitalize
  };
}

export {
  capitalize,
  uncapitalize,
  splitIntoWords,
  pascalCase,
  camelCase,
  kebabCase,
  snakeCase,
  upper,
  lower,
  trim,
  title,
  makeHelpers,
}
/* No side effect */
