// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function injectRegex(content, pattern, replacement) {
  try {
    let regex = new RegExp(pattern);
    let result = Js_string.replaceByRe(regex, content, replacement);
    return {
      TAG: "Ok",
      _0: result
    };
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: "Invalid regex pattern: " + pattern
      };
    }
    throw exn;
  }
}

function insertAfter(content, pattern, insertion) {
  try {
    let regex = new RegExp(pattern);
    let result = Js_string.replaceByRe(regex, content, "$&" + insertion);
    return {
      TAG: "Ok",
      _0: result
    };
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: "Invalid regex pattern: " + pattern
      };
    }
    throw exn;
  }
}

function insertBefore(content, pattern, insertion) {
  try {
    let regex = new RegExp(pattern);
    let result = Js_string.replaceByRe(regex, content, insertion + "$&");
    return {
      TAG: "Ok",
      _0: result
    };
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: "Invalid regex pattern: " + pattern
      };
    }
    throw exn;
  }
}

function prependToContent(content, prepend) {
  return prepend + "\n" + content;
}

function appendToContent(content, append) {
  return content + "\n" + append;
}

function apply(existingContent, renderedContent, directive) {
  if (typeof directive !== "object") {
    switch (directive) {
      case "Prepend" :
        return {
          TAG: "Ok",
          _0: {
            content: prependToContent(existingContent, renderedContent),
            applied: true
          }
        };
      case "Append" :
        return {
          TAG: "Ok",
          _0: {
            content: appendToContent(existingContent, renderedContent),
            applied: true
          }
        };
      default:
        return {
          TAG: "Ok",
          _0: {
            content: existingContent,
            applied: false
          }
        };
    }
  } else {
    switch (directive.TAG) {
      case "Inject" :
        let result = injectRegex(existingContent, directive._0, renderedContent);
        return Stdlib_Result.map(result, content => ({
          content: content,
          applied: true
        }));
      case "After" :
        let result$1 = insertAfter(existingContent, directive._0, renderedContent);
        return Stdlib_Result.map(result$1, content => ({
          content: content,
          applied: true
        }));
      case "Before" :
        let result$2 = insertBefore(existingContent, directive._0, renderedContent);
        return Stdlib_Result.map(result$2, content => ({
          content: content,
          applied: true
        }));
      default:
        return {
          TAG: "Ok",
          _0: {
            content: existingContent,
            applied: false
          }
        };
    }
  }
}

export {
  injectRegex,
  insertAfter,
  insertBefore,
  prependToContent,
  appendToContent,
  apply,
}
/* No side effect */
