// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Readline from "readline";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function askPrompt(rl, prompt) {
  let d = prompt.default;
  let questionText = prompt.description + (
    d !== undefined ? " [" + d + "]" : ""
  ) + ": ";
  let match = prompt.promptType;
  switch (match) {
    case "Input" :
      return rl.question(questionText, undefined);
    case "Select" :
      let opts = prompt.options;
      if (opts === undefined) {
        return rl.question(questionText, undefined);
      }
      if (opts.length === 0) {
        return rl.question(questionText, undefined);
      }
      let optionsText = opts.map((opt, i) => "  " + (i + 1 | 0).toString() + ". " + opt).join("\n");
      let fullQuestion = optionsText + "\n" + questionText;
      return rl.question(fullQuestion, undefined).then(answer => {
        let trimmedAnswer = answer.trim();
        let n = Stdlib_Int.fromString(trimmedAnswer, undefined);
        let idx = n !== undefined ? n - 1 | 0 : 0;
        let s = opts[idx];
        return Promise.resolve(s !== undefined ? s : "");
      });
    case "Confirm" :
      return rl.question(questionText + " (y/n) ", undefined).then(answer => {
        let trimmed = answer.trim().toLowerCase();
        if (trimmed === "y" || trimmed === "yes" || trimmed === "") {
          return Promise.resolve("true");
        } else {
          return Promise.resolve("false");
        }
      });
  }
}

function resolve(rl, prompts, force) {
  let answers = {};
  if (force) {
    prompts.forEach(p => {
      let d = p.default;
      if (d !== undefined) {
        answers[p.name] = d;
      } else {
        answers[p.name] = "";
      }
    });
    return Promise.resolve(answers);
  }
  let loop = (idx, prompts) => {
    if (idx >= prompts.length) {
      return Promise.resolve(answers);
    }
    let prompt = prompts[idx];
    if (prompt !== undefined) {
      return askPrompt(rl, prompt).then(answer => {
        let finalAnswer = answer.trim() === "" ? Stdlib_Option.getOr(prompt.default, "") : answer;
        answers[prompt.name] = finalAnswer;
        return loop(idx + 1 | 0, prompts);
      });
    } else {
      return Promise.resolve(answers);
    }
  };
  return loop(0, prompts).then(param => Promise.resolve(answers));
}

function createReadline() {
  return Readline.createInterface(undefined, undefined);
}

function closeReadline(rl) {
  rl.close();
}

export {
  askPrompt,
  resolve,
  createReadline,
  closeReadline,
}
/* readline Not a pure module */
