// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

let frontmatterRegex = /^---\\n([\\s\\S]*?)\\n---\\n/;

let directiveRegex = /^(\\w+):\\s*(.*)$/;

function checkDirective(key, value) {
  if (key === "to") {
    return {
      TAG: "To",
      _0: value
    };
  } else if (key === "inject") {
    return {
      TAG: "Inject",
      _0: value
    };
  } else if (key === "after") {
    return {
      TAG: "After",
      _0: value
    };
  } else if (key === "before") {
    return {
      TAG: "Before",
      _0: value
    };
  } else if (key === "prepend" && (value === "" || value === "true")) {
    return "Prepend";
  } else if (key === "append" && (value === "" || value === "true")) {
    return "Append";
  } else if (key === "force" && (value === "" || value === "true")) {
    return "Force";
  } else if (key === "sh") {
    return {
      TAG: "Sh",
      _0: value
    };
  } else {
    return;
  }
}

function parseDirective(line) {
  let matches = Js_string.match_(directiveRegex, line);
  if (matches === undefined) {
    return;
  }
  if (matches.length < 3) {
    return;
  }
  let keyOpt = matches[1];
  let valueOpt = matches[2];
  if (keyOpt !== undefined && valueOpt !== undefined) {
    return checkDirective(keyOpt, valueOpt);
  }
}

function parse(content) {
  let matches = Js_string.match_(frontmatterRegex, content);
  if (matches === undefined) {
    return {
      TAG: "Error",
      _0: "Missing or invalid frontmatter delimiter"
    };
  }
  if (matches.length < 2) {
    return {
      TAG: "Error",
      _0: "Missing or invalid frontmatter delimiter"
    };
  }
  let fsOpt = matches[1];
  if (fsOpt === undefined) {
    return {
      TAG: "Error",
      _0: "Missing frontmatter content"
    };
  }
  let body = Js_string.replaceByRe(frontmatterRegex, content, "");
  let lines = Js_string.split(fsOpt, "\n").filter(l => l !== "");
  let directives = Stdlib_Array.filterMap(lines.map(parseDirective), x => x);
  return {
    TAG: "Ok",
    _0: {
      directives: directives,
      body: body
    }
  };
}

export {
  frontmatterRegex,
  directiveRegex,
  checkDirective,
  parseDirective,
  parse,
}
/* No side effect */
