// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ejs from "ejs";
import * as FuncMap from "./FuncMap.mjs";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function render(tmpl, ctx) {
  let helpers = FuncMap.makeHelpers();
  let data = {};
  data["name"] = ctx.name;
  data["Name"] = ctx.pascalName;
  data["names"] = ctx.names;
  data["Names"] = ctx.pluralPascalName;
  data["cwd"] = ctx.cwd;
  data["actionfolder"] = ctx.actionfolder;
  Object.entries(ctx.attributes).forEach(param => {
    data[param[0]] = param[1];
  });
  let hObj = {};
  hObj["pascalCase"] = helpers.pascalCase;
  hObj["camelCase"] = helpers.camelCase;
  hObj["kebabCase"] = helpers.kebabCase;
  hObj["snakeCase"] = helpers.snakeCase;
  hObj["upper"] = helpers.upper;
  hObj["lower"] = helpers.lower;
  hObj["trim"] = helpers.trim;
  hObj["title"] = helpers.title;
  data["h"] = hObj;
  try {
    let rendered = Ejs.render(tmpl.body, data);
    return {
      TAG: "Ok",
      _0: rendered
    };
  } catch (raw_obj) {
    let obj = Primitive_exceptions.internalToException(raw_obj);
    if (obj.RE_EXN_ID === "JsExn") {
      let m = Stdlib_JsExn.message(obj._1);
      let msg = m !== undefined ? m : "Unknown render error";
      return {
        TAG: "Error",
        _0: msg
      };
    }
    throw obj;
  }
}

export {
  render,
}
/* ejs Not a pure module */
