// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Nodechild_process from "node:child_process";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

async function execShellCommand(command, cwd) {
  try {
    let options_shell = true;
    let options_encoding = "utf8";
    let options = {
      cwd: cwd,
      shell: options_shell,
      encoding: options_encoding
    };
    let result = await Nodechild_process.exec(command, options);
    let match = result.status;
    if (match === 0) {
      return {
        TAG: "Ok",
        _0: result.stdout
      };
    } else {
      return {
        TAG: "Error",
        _0: result.stderr
      };
    }
  } catch (raw_obj) {
    let obj = Primitive_exceptions.internalToException(raw_obj);
    if (obj.RE_EXN_ID === "JsExn") {
      let m = Stdlib_JsExn.message(obj._1);
      let message = m !== undefined ? m : "Unknown error";
      return {
        TAG: "Error",
        _0: message
      };
    }
    throw obj;
  }
}

export {
  execShellCommand,
}
/* Stdlib_JsExn Not a pure module */
