// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ChildProcess from "../bindings/ChildProcess.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Promises from "node:fs/promises";

function executeShellCommands(commands, cwd) {
  let count = {
    contents: 0
  };
  let promise = Stdlib_Array.reduce(commands, Promise.resolve({
    TAG: "Ok",
    _0: undefined
  }), (acc, cmd) => acc.then(r => {
    if (r.TAG === "Ok") {
      return ChildProcess.execShellCommand(cmd.command, cwd).then(result => {
        if (result.TAG !== "Ok") {
          return Promise.resolve({
            TAG: "Error",
            _0: "Shell command failed: " + result._0
          });
        }
        count.contents = count.contents + 1 | 0;
        return Promise.resolve({
          TAG: "Ok",
          _0: undefined
        });
      });
    } else {
      return Promise.resolve({
        TAG: "Error",
        _0: r._0
      });
    }
  }));
  return promise.then(r => {
    if (r.TAG === "Ok") {
      return Promise.resolve({
        TAG: "Ok",
        _0: count.contents
      });
    } else {
      return Promise.resolve({
        TAG: "Error",
        _0: r._0
      });
    }
  });
}

function commitFiles(stagingDir, outputDir, renderedFiles) {
  return Promise.resolve({
    TAG: "Ok",
    _0: 0
  });
}

async function rollback(stagingDir) {
  try {
    return await Promises.rm(stagingDir, {
      recursive: true
    });
  } catch (exn) {
    return;
  }
}

async function run(stagingDir, outputDir, renderedFiles, shellCommands) {
  let commitResult = await commitFiles(stagingDir, outputDir, renderedFiles);
  if (commitResult.TAG === "Ok") {
    let count = commitResult._0;
    let shellResult = await executeShellCommands(shellCommands, outputDir);
    if (shellResult.TAG !== "Ok") {
      return {
        TAG: "Ok",
        _0: {
          filesCreated: count,
          filesInjected: 0,
          commandsExecuted: 0
        }
      };
    }
    await rollback(stagingDir);
    return {
      TAG: "Ok",
      _0: {
        filesCreated: count,
        filesInjected: 0,
        commandsExecuted: shellResult._0
      }
    };
  }
  await rollback(stagingDir);
  return {
    TAG: "Error",
    _0: commitResult._0
  };
}

export {
  executeShellCommands,
  commitFiles,
  rollback,
  run,
}
/* ChildProcess Not a pure module */
