// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "../bindings/Fs.mjs";
import * as Nodepath from "node:path";
import * as PromptResolver from "../PromptResolver.mjs";

async function checkFileConflict(sourcePath, targetPath, outputDir) {
  let fullTargetPath = Nodepath.join(outputDir, targetPath);
  let exists = await Fs.fileExists(fullTargetPath);
  if (exists) {
    return {
      sourcePath: sourcePath,
      targetPath: fullTargetPath
    };
  }
}

async function detectConflicts(templates, outputDir, force) {
  return [];
}

async function run(rl, generator, _context, outputDir, force) {
  let m = generator.manifest;
  let prompts = m !== undefined ? m.prompts : undefined;
  let resolvedAttributes = prompts !== undefined ? (
      prompts.length !== 0 ? await PromptResolver.resolve(rl, prompts, force) : ({})
    ) : ({});
  let conflicts = await detectConflicts(generator.templates, outputDir, force);
  return {
    TAG: "Ok",
    _0: {
      resolvedAttributes: resolvedAttributes,
      conflicts: conflicts
    }
  };
}

export {
  checkFileConflict,
  detectConflicts,
  run,
}
/* Fs Not a pure module */
