// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "../bindings/Fs.mjs";
import * as Yaml from "yaml";
import * as Js_math from "@rescript/runtime/lib/es6/Js_math.js";
import * as Nodepath from "node:path";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Promises from "node:fs/promises";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function parseHooks(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return;
  }
  let v = json["pre_generate"];
  let preGenerate = typeof v === "string" ? v : undefined;
  let v$1 = json["post_generate"];
  let postGenerate = typeof v$1 === "string" ? v$1 : undefined;
  let v$2 = json["timeout"];
  let timeout = typeof v$2 === "number" ? Js_math.floor(v$2) : undefined;
  if (preGenerate === undefined && postGenerate === undefined && timeout === undefined) {
    return;
  } else {
    return {
      preGenerate: preGenerate,
      postGenerate: postGenerate,
      timeout: timeout
    };
  }
}

function parse(yamlContent) {
  try {
    let json = Yaml.parse(yamlContent);
    if (typeof json !== "object" || json === null || Array.isArray(json)) {
      return {
        TAG: "Ok",
        _0: {
          hooks: undefined,
          output: undefined
        }
      };
    }
    let v = json["hooks"];
    let hooks = v !== undefined ? parseHooks(v) : undefined;
    let v$1 = json["output"];
    let output = typeof v$1 === "string" ? v$1 : undefined;
    return {
      TAG: "Ok",
      _0: {
        hooks: hooks,
        output: output
      }
    };
  } catch (raw_obj) {
    let obj = Primitive_exceptions.internalToException(raw_obj);
    if (obj.RE_EXN_ID === "JsExn") {
      let m = Stdlib_JsExn.message(obj._1);
      let msg = m !== undefined ? m : "Failed to parse config";
      return {
        TAG: "Error",
        _0: msg
      };
    }
    throw obj;
  }
}

async function loadFrom(dir) {
  let configPath = Nodepath.join(dir, ".fluxo.yaml");
  let exists = await Fs.fileExists(configPath);
  if (!exists) {
    return {
      TAG: "Ok",
      _0: undefined
    };
  }
  try {
    let content = await Promises.readFile(configPath, {
      encoding: "utf8"
    });
    let result = parse(content);
    if (result.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: result._0
      };
    } else {
      return {
        TAG: "Error",
        _0: result._0
      };
    }
  } catch (raw_obj) {
    let obj = Primitive_exceptions.internalToException(raw_obj);
    if (obj.RE_EXN_ID === "JsExn") {
      let m = Stdlib_JsExn.message(obj._1);
      let msg = m !== undefined ? m : "Failed to read config";
      return {
        TAG: "Error",
        _0: msg
      };
    }
    throw obj;
  }
}

let defaultOutputDir = "generated";

let defaultTimeout = 5;

export {
  parseHooks,
  parse,
  loadFrom,
  defaultOutputDir,
  defaultTimeout,
}
/* Fs Not a pure module */
