// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Promises from "node:fs/promises";

async function fileExists(path) {
  try {
    await Promises.access(path, 0);
    return true;
  } catch (exn) {
    return false;
  }
}

let fOk = 0;

export {
  fOk,
  fileExists,
}
/* node:fs/promises Not a pure module */
