// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodeos from "node:os";
import * as Nodepath from "node:path";

function makeStagingDir() {
  let randomPart = Math.random().toString().slice(2);
  return Nodepath.join(Nodeos.tmpdir(), "fluxo-" + randomPart);
}

export {
  makeStagingDir,
}
/* node:os Not a pure module */
