// Generated by ReScript, PLEASE EDIT WITH CARE


function parseOptions(short, $$default, param) {
  return {
    type: "string",
    short: short,
    default: $$default
  };
}

function getString(values, key) {
  return values[key];
}

function getBool(values, key) {
  let v = values[key];
  if (v !== undefined) {
    if (v === "true") {
      return true;
    } else {
      return v === "false";
    }
  } else {
    return false;
  }
}

export {
  parseOptions,
  getString,
  getBool,
}
/* No side effect */
