// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "../bindings/Fs.mjs";
import * as Manifest from "../../domain/manifest/Manifest.mjs";
import * as Nodepath from "node:path";
import * as Frontmatter from "../../domain/template/Frontmatter.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Promises from "node:fs/promises";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function isTemplateFile(filename) {
  if (filename.endsWith(".ejs.t")) {
    return true;
  } else {
    return filename.endsWith(".tmpl");
  }
}

function isManifestFile(filename) {
  return filename === "manifest.yaml";
}

async function loadTemplate(sourcePath) {
  try {
    let content = await Promises.readFile(sourcePath, {
      encoding: "utf8"
    });
    let filename = Nodepath.basename(sourcePath);
    if (filename === "manifest.yaml") {
      return {
        TAG: "Error",
        _0: "Skipping manifest file"
      };
    }
    let parsed = Frontmatter.parse(content);
    if (parsed.TAG !== "Ok") {
      return {
        TAG: "Error",
        _0: "Failed to parse frontmatter in " + sourcePath + ": " + parsed._0
      };
    }
    let parsed$1 = parsed._0;
    return {
      TAG: "Ok",
      _0: {
        sourcePath: sourcePath,
        directives: parsed$1.directives,
        body: parsed$1.body
      }
    };
  } catch (raw_obj) {
    let obj = Primitive_exceptions.internalToException(raw_obj);
    if (obj.RE_EXN_ID === "JsExn") {
      let m = Stdlib_JsExn.message(obj._1);
      let msg = m !== undefined ? "Failed to load template " + sourcePath + ": " + m : "Failed to load template " + sourcePath;
      return {
        TAG: "Error",
        _0: msg
      };
    }
    throw obj;
  }
}

async function loadManifest(generatorPath) {
  let manifestPath = Nodepath.join(generatorPath, "manifest.yaml");
  let exists = await Fs.fileExists(manifestPath);
  if (!exists) {
    return;
  }
  try {
    let content = await Promises.readFile(manifestPath, {
      encoding: "utf8"
    });
    let m = Manifest.parse(content);
    if (m.TAG === "Ok") {
      return m._0;
    } else {
      return;
    }
  } catch (exn) {
    return;
  }
}

async function discoverIn(_baseDir) {
  return [];
}

async function discover(searchPaths, param) {
  let defaultPaths = [
    "_templates",
    "templates",
    "generators"
  ];
  let paths = searchPaths !== undefined ? searchPaths : defaultPaths;
  let allGenPromises = paths.map(discoverIn);
  let allResults = await Promise.all(allGenPromises);
  return Stdlib_Array.reduce(allResults, [], (acc, gens) => acc.concat(gens));
}

function findByClassification(generators, classification) {
  return generators.find(g => g.name === classification);
}

export {
  isTemplateFile,
  isManifestFile,
  loadTemplate,
  loadManifest,
  discoverIn,
  discover,
  findByClassification,
}
/* Fs Not a pure module */
