// Init — scaffold .blueprint.yaml and hello-world template in current working directory
let runInit: (~deps: Ports.deps) => promise<unit> = async (~deps) => {
  let cwd = deps.process.cwd()
  let configPath = deps.path.join(cwd, ".blueprint.yaml")

  let configContent = "# Blueprint configuration\n# Generated by Blueprint\n\ngenerators: []\nhooks:\n  pre_generate: \"\"\n  post_generate: \"\"\n  timeout: 5s"

  let helloWorldTemplate = "---\nto: hello-<%= name %>.md\n---\n# Hello, <%= name %>!\n\nGenerated by Blueprint. Edit _templates/hello-world/new/hello.ejs.t to customize.\n"

  let created = []
  let skipped = []

  let configExists = await deps.fs.fileExists(configPath)
  if configExists {
    skipped->Array.push(".blueprint.yaml")
  } else {
    await deps.fs.writeFile(configPath, configContent)
    created->Array.push(".blueprint.yaml")
  }

  let templateDir = deps.path.join(deps.path.join(cwd, "_templates"), "hello-world/new")
  let _ = await deps.fs.mkdir(templateDir, ~options={recursive: true})

  let examplePath = deps.path.join(templateDir, "hello.ejs.t")
  let exampleExists = await deps.fs.fileExists(examplePath)
  if exampleExists {
    skipped->Array.push("_templates/hello-world/new/hello.ejs.t")
  } else {
    await deps.fs.writeFile(examplePath, helloWorldTemplate, ~options={encoding: "utf8"})
    created->Array.push("_templates/hello-world/new/hello.ejs.t")
  }

  if created->Array.length > 0 {
    Console.log("Created: " ++ created->Array.join(", "))
  }
  if skipped->Array.length > 0 {
    Console.log("Skipped (already exists): " ++ skipped->Array.join(", "))
  }
}
