// Init — scaffold .blueprint.yaml in current working directory
let runInit: (~deps: Ports.deps) => promise<unit> = async (~deps) => {
  let cwd = deps.process.cwd()
  let configPath = deps.path.join(cwd, ".blueprint.yaml")

  let exists = await deps.fs.fileExists(configPath)
  if exists {
    Console.error("Error: .blueprint.yaml already exists at " ++ configPath)
    deps.process.exit(1)
  } else {
    let content = "# Blueprint configuration\n# Generated by Blueprint\n\ngenerators: []\nhooks:\n  pre_generate: \"\"\n  post_generate: \"\"\n  timeout: 5s"
    await deps.fs.writeFile(configPath, content)
    Console.log("Scaffolded .blueprint.yaml at " ++ configPath)
  }
}
