// InitGlobal — scaffold ~/.config/blueprint/config.yaml and global hello-world template
let runInitGlobal: (~deps: Ports.deps) => promise<unit> = async (~deps) => {
  let homeDir = deps.process.homedir()
  let configDir = deps.path.join(deps.path.join(homeDir, ".config"), "blueprint")
  let configPath = deps.path.join(configDir, "config.yaml")

  let configContent = "# Global Blueprint configuration\n# Loaded from ~/.config/blueprint/config.yaml\n\ntemplates: []\nforce_overwrite: false\ndry_run: false\ntimeout: 5\ndefault_attributes: {}\nregistry: []\n"

  let helloWorldTemplate = "---\nto: hello-<%= name %>.md\n---\n# Hello, <%= name %>!\n\nGenerated by Blueprint. Edit _templates/hello-world/new/hello.ejs.t to customize.\n"

  let manifestContent = "name: hello-world\nclassification: hello-world\nprompts:\n  - name: name\n    type: input\n    description: \"Name to greet in the generated file\"\n    default: world\n"

  let created = []
  let skipped = []

  let configExists = await deps.fs.fileExists(configPath)
  if configExists {
    skipped->Array.push("global config")
  } else {
    let dirExists = await deps.fs.fileExists(configDir)
    if !dirExists {
      let _ = await deps.fs.mkdir(configDir, ~options={recursive: true})
    }
    let _ = await deps.fs.writeFile(configPath, configContent)
    created->Array.push("global config")
  }

  let globalRoot = Utils.globalTemplateRegistryRoot(~deps)
  let helloWorldRoot = deps.path.join(globalRoot, "hello-world")
  let exampleDir = deps.path.join(helloWorldRoot, "new")
  let _ = await deps.fs.mkdir(exampleDir, ~options={recursive: true})

  let manifestPath = deps.path.join(helloWorldRoot, "manifest.yaml")
  let manifestExists = await deps.fs.fileExists(manifestPath)
  if manifestExists {
    skipped->Array.push("global hello-world manifest")
  } else {
    await deps.fs.writeFile(manifestPath, manifestContent, ~options={encoding: "utf8"})
    created->Array.push("global hello-world manifest")
  }

  let examplePath = deps.path.join(exampleDir, "hello.ejs.t")
  let exampleExists = await deps.fs.fileExists(examplePath)
  if exampleExists {
    skipped->Array.push("global hello-world template")
  } else {
    await deps.fs.writeFile(examplePath, helloWorldTemplate, ~options={encoding: "utf8"})
    created->Array.push("global hello-world template")
  }

  if created->Array.length > 0 {
    Console.log("Created: " ++ created->Array.join(", "))
  }
  if skipped->Array.length > 0 {
    Console.log("Skipped (already exists): " ++ skipped->Array.join(", "))
  }
}
