// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Os from "../../infrastructure/bindings/Os.mjs";
import * as Ejs from "ejs";
import * as Context from "../../domain/context/Context.mjs";
import * as Renderer from "../../infrastructure/rendering/Renderer.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Promises from "node:fs/promises";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function resolveTargetPath(directive, ctx) {
  if (typeof directive !== "object") {
    return;
  }
  if (directive.TAG !== "To") {
    return;
  }
  let data = {};
  data["name"] = ctx.nameVariants.name;
  data["Name"] = ctx.nameVariants.pascalName;
  data["names"] = ctx.nameVariants.names;
  data["Names"] = ctx.nameVariants.pluralPascalName;
  data["cwd"] = ctx.cwd;
  data["actionfolder"] = ctx.actionfolder;
  Object.entries(ctx.attributes).forEach(param => {
    data[param[0]] = param[1];
  });
  try {
    return Ejs.render(directive._0, data);
  } catch (exn) {
    return;
  }
}

async function renderTemplate(template, context) {
  let renderCtx = Context.toRenderContext(context);
  let renderedBody = Renderer.render(template, renderCtx);
  if (renderedBody.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: "Failed to render template " + template.sourcePath + ": " + renderedBody._0
    };
  }
  let targetPathOpt = Stdlib_Option.flatMap(template.directives.find(d => {
    if (typeof d !== "object") {
      return false;
    } else {
      return d.TAG === "To";
    }
  }), d => resolveTargetPath(d, context));
  let shellCmds = Stdlib_Array.filterMap(template.directives, d => {
    if (typeof d !== "object" || d.TAG !== "Sh") {
      return;
    } else {
      return {
        command: d._0,
        sourcePath: template.sourcePath
      };
    }
  });
  if (targetPathOpt !== undefined) {
    return {
      TAG: "Ok",
      _0: [
        template.sourcePath,
        targetPathOpt,
        renderedBody._0,
        shellCmds
      ]
    };
  } else {
    return {
      TAG: "Error",
      _0: "No 'to' directive found in template: " + template.sourcePath
    };
  }
}

async function run(_templates, _context, _outputDir, _conflictDecisions) {
  let stagingDir = Os.makeStagingDir();
  let mkdirResult;
  try {
    await Promises.mkdir(stagingDir, {
      recursive: true
    });
    mkdirResult = {
      TAG: "Ok",
      _0: undefined
    };
  } catch (raw_obj) {
    let obj = Primitive_exceptions.internalToException(raw_obj);
    if (obj.RE_EXN_ID === "JsExn") {
      let m = Stdlib_JsExn.message(obj._1);
      let msg = m !== undefined ? "Failed to create staging dir: " + m : "Failed to create staging dir";
      mkdirResult = {
        TAG: "Error",
        _0: {
          stagingDir: stagingDir,
          message: msg
        }
      };
    } else {
      throw obj;
    }
  }
  if (mkdirResult.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: mkdirResult._0
    };
  }
  let renderedFiles = [];
  let shellCommands = [];
  return {
    TAG: "Ok",
    _0: {
      stagingDir: stagingDir,
      renderedFiles: renderedFiles,
      shellCommands: shellCommands
    }
  };
}

export {
  resolveTargetPath,
  renderTemplate,
  run,
}
/* Os Not a pure module */
