// Generated by ReScript, PLEASE EDIT WITH CARE


function parseChoice(input) {
  let trimmed = input.trim().toLowerCase();
  switch (trimmed) {
    case "abort" :
      return "Abort";
    case "n" :
    case "no" :
    case "q" :
      return "NoAll";
    case "s" :
    case "select" :
      return "Select";
    case "a" :
    case "all" :
    case "y" :
    case "yes" :
      return "YesAll";
    default:
      return;
  }
}

function promptBulkResolution(rl, count) {
  let promptText = "\n" + count.toString() + " file(s) already exist. Overwrite all? [y]es / [n]o / [s]elect / [a]bort: ";
  let loop = () => rl.question(promptText, undefined).then(answer => {
    let r = parseChoice(answer);
    if (r !== undefined) {
      return Promise.resolve(r);
    } else {
      return loop();
    }
  });
  return loop();
}

function resolveConflicts(rl, conflicts, force) {
  if (!force) {
    if (conflicts.length === 0) {
      return Promise.resolve({
        TAG: "Ok",
        _0: []
      });
    } else {
      return promptBulkResolution(rl, conflicts.length).then(resolution => {
        switch (resolution) {
          case "YesAll" :
            let decisions = conflicts.map(c => ({
              sourcePath: c.sourcePath,
              targetPath: c.targetPath,
              overwrite: true
            }));
            return Promise.resolve({
              TAG: "Ok",
              _0: decisions
            });
          case "NoAll" :
            let decisions$1 = conflicts.map(c => ({
              sourcePath: c.sourcePath,
              targetPath: c.targetPath,
              overwrite: false
            }));
            return Promise.resolve({
              TAG: "Ok",
              _0: decisions$1
            });
          case "Select" :
            let decisions$2 = [];
            let loop = (idx, conflicts) => {
              if (idx >= conflicts.length) {
                return Promise.resolve({
                  TAG: "Ok",
                  _0: decisions$2
                });
              }
              let c = conflicts[idx];
              if (c !== undefined) {
                return rl.question("Overwrite " + c.targetPath + "? [y]es / [n]o: ", undefined).then(answer => {
                  let match = parseChoice(answer);
                  let overwrite;
                  if (match !== undefined) {
                    switch (match) {
                      case "YesAll" :
                      case "NoAll" :
                        overwrite = false;
                        break;
                      case "Select" :
                      case "Abort" :
                        overwrite = true;
                        break;
                    }
                  } else {
                    overwrite = false;
                  }
                  decisions$2.push({
                    sourcePath: c.sourcePath,
                    targetPath: c.targetPath,
                    overwrite: overwrite
                  });
                  return loop(idx + 1 | 0, conflicts);
                });
              } else {
                return Promise.resolve({
                  TAG: "Ok",
                  _0: decisions$2
                });
              }
            };
            return loop(0, conflicts);
          case "Abort" :
            return Promise.resolve({
              TAG: "Error",
              _0: "Aborted by user"
            });
        }
      });
    }
  }
  let decisions = conflicts.map(c => ({
    sourcePath: c.sourcePath,
    targetPath: c.targetPath,
    overwrite: true
  }));
  return Promise.resolve({
    TAG: "Ok",
    _0: decisions
  });
}

export {
  parseChoice,
  promptBulkResolution,
  resolveConflicts,
}
/* No side effect */
