// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FuncMap from "./templates/FuncMap.mjs";

function makeNameVariants(baseName) {
  return {
    name: FuncMap.snakeCase(baseName).toLowerCase(),
    pascalName: FuncMap.pascalCase(baseName),
    names: FuncMap.snakeCase(baseName).toLowerCase().concat("s"),
    pluralPascalName: FuncMap.pascalCase(baseName).concat("s")
  };
}

function mergeAttributes(cliAttributes, promptAnswers, manifestDefaults, nameVariants) {
  let merged = {};
  Object.entries(manifestDefaults).forEach(param => {
    merged[param[0]] = param[1];
  });
  merged["name"] = nameVariants.name;
  merged["Name"] = nameVariants.pascalName;
  merged["names"] = nameVariants.names;
  merged["Names"] = nameVariants.pluralPascalName;
  Object.entries(promptAnswers).forEach(param => {
    merged[param[0]] = param[1];
  });
  Object.entries(cliAttributes).forEach(param => {
    merged[param[0]] = param[1];
  });
  return merged;
}

function build(cwd, actionfolder, name, cliAttributes, promptAnswers, manifestDefaults, param) {
  let nv = makeNameVariants(name);
  let defaults = manifestDefaults !== undefined ? manifestDefaults : ({});
  let prompts = promptAnswers !== undefined ? promptAnswers : ({});
  let cli = cliAttributes !== undefined ? cliAttributes : ({});
  return {
    cwd: cwd,
    actionfolder: actionfolder,
    nameVariants: nv,
    attributes: mergeAttributes(cli, prompts, defaults, nv)
  };
}

function toRenderContext(ctx) {
  return {
    name: ctx.nameVariants.name,
    pascalName: ctx.nameVariants.pascalName,
    names: ctx.nameVariants.names,
    pluralPascalName: ctx.nameVariants.pluralPascalName,
    cwd: ctx.cwd,
    actionfolder: ctx.actionfolder,
    attributes: ctx.attributes
  };
}

export {
  makeNameVariants,
  mergeAttributes,
  build,
  toRenderContext,
}
/* No side effect */
