// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Config from "./Config.mjs";

async function run(generator, _name, _cliAttributes, _outputDir, _force) {
  return {
    TAG: "Ok",
    _0: {
      filesCreated: 0,
      filesInjected: 0,
      commandsExecuted: 0,
      classification: generator.name
    }
  };
}

async function runWithConfig(generator, name, cliAttributes, force) {
  return await run(generator, name, cliAttributes, Config.defaultOutputDir, force);
}

export {
  run,
  runWithConfig,
}
/* Config Not a pure module */
