// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Nodechild_process from "node:child_process";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function parseCommand(cmd) {
  let parts = cmd.split(" ");
  let p = parts[0];
  let interpreter = p !== undefined ? p : "bash";
  let sliced = parts.slice(1);
  let args = sliced.join(" ");
  return [
    interpreter,
    args
  ];
}

async function executeHook(command, cwd, timeout) {
  let match = parseCommand(command);
  try {
    let fullCmd = match[0] + " " + match[1];
    let result = await Nodechild_process.exec(fullCmd, {
      cwd: cwd,
      shell: true,
      encoding: "utf8",
      timeout: timeout
    });
    let code = result.status;
    let exitCode = code !== undefined ? code : 0;
    if (exitCode === 0) {
      return {
        TAG: "Ok",
        _0: {
          hookType: "PreGenerate",
          output: result.stdout,
          exitCode: exitCode
        }
      };
    } else {
      return {
        TAG: "Error",
        _0: "Hook exited with code " + exitCode.toString() + ": " + result.stderr
      };
    }
  } catch (raw_obj) {
    let obj = Primitive_exceptions.internalToException(raw_obj);
    if (obj.RE_EXN_ID === "JsExn") {
      let m = Stdlib_JsExn.message(obj._1);
      let msg = m !== undefined ? "Hook execution failed: " + m : "Hook execution failed";
      return {
        TAG: "Error",
        _0: msg
      };
    }
    throw obj;
  }
}

async function run(config, cwd) {
  let h = config.hooks;
  let timeout;
  if (h !== undefined) {
    let t = h.timeout;
    timeout = t !== undefined ? t * 1000 | 0 : 5000;
  } else {
    timeout = 5000;
  }
  let h$1 = config.hooks;
  let preResult;
  if (h$1 !== undefined) {
    let cmd = h$1.preGenerate;
    if (cmd !== undefined) {
      let result = await executeHook(cmd, cwd, timeout);
      preResult = result.TAG === "Ok" ? ({
          TAG: "Ok",
          _0: undefined
        }) : ({
          TAG: "Error",
          _0: "pre_generate hook failed: " + result._0
        });
    } else {
      preResult = {
        TAG: "Ok",
        _0: undefined
      };
    }
  } else {
    preResult = {
      TAG: "Ok",
      _0: undefined
    };
  }
  if (preResult.TAG !== "Ok") {
    return preResult;
  }
  let h$2 = config.hooks;
  if (h$2 === undefined) {
    return {
      TAG: "Ok",
      _0: undefined
    };
  }
  let cmd$1 = h$2.postGenerate;
  if (cmd$1 === undefined) {
    return {
      TAG: "Ok",
      _0: undefined
    };
  }
  let result$1 = await executeHook(cmd$1, cwd, timeout);
  if (result$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: undefined
    };
  } else {
    return {
      TAG: "Error",
      _0: "post_generate hook failed: " + result$1._0
    };
  }
}

export {
  parseCommand,
  executeHook,
  run,
}
/* Stdlib_JsExn Not a pure module */
