// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Yaml from "yaml";
import * as Js_array from "@rescript/runtime/lib/es6/Js_array.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function parsePromptType(s) {
  switch (s) {
    case "confirm" :
      return "Confirm";
    case "input" :
      return "Input";
    case "select" :
      return "Select";
    default:
      return;
  }
}

function promptTypeToString(pt) {
  switch (pt) {
    case "Input" :
      return "input";
    case "Select" :
      return "select";
    case "Confirm" :
      return "confirm";
  }
}

function parse(yamlContent) {
  try {
    let json = Yaml.parse(yamlContent);
    let getString = (obj, key) => {
      if (typeof obj !== "object" || obj === null || Array.isArray(obj)) {
        return;
      }
      let v = obj[key];
      if (typeof v === "string") {
        return v;
      }
    };
    let getOptString = (obj, key) => {
      let s = getString(obj, key);
      if (s !== undefined) {
        return s;
      }
    };
    let getStringArray = (obj, key) => {
      if (typeof obj !== "object" || obj === null || Array.isArray(obj)) {
        return;
      }
      let v = obj[key];
      if (Array.isArray(v)) {
        return Stdlib_Array.filterMap(v.map(v$p => {
          if (typeof v$p === "string") {
            return v$p;
          }
        }), x => x);
      }
    };
    let getMetadata = (obj, key) => {
      if (typeof obj !== "object" || obj === null || Array.isArray(obj)) {
        return;
      }
      let v = obj[key];
      if (typeof v === "object" && v !== null && !Array.isArray(v)) {
        return v;
      }
    };
    let getPrompts = (obj, key) => {
      if (typeof obj !== "object" || obj === null || Array.isArray(obj)) {
        return;
      }
      let v = obj[key];
      if (Array.isArray(v)) {
        return Stdlib_Array.filterMap(v.map(promptJson => {
          if (typeof promptJson !== "object" || promptJson === null || Array.isArray(promptJson)) {
            return;
          }
          let name = getString(promptJson, "name");
          let desc = Stdlib_Option.getOr(getString(promptJson, "description"), "");
          let defaultVal = getOptString(promptJson, "default");
          let opts = getStringArray(promptJson, "options");
          let typeStr = Stdlib_Option.getOr(getString(promptJson, "type"), "input");
          let pt = Stdlib_Option.getOr(parsePromptType(typeStr), "Input");
          if (name !== undefined) {
            return {
              name: name,
              promptType: pt,
              description: desc,
              default: defaultVal,
              options: opts
            };
          }
        }), x => x);
      }
    };
    let name = Stdlib_Option.getOr(getString(json, "name"), "");
    let classification = Stdlib_Option.getOr(getString(json, "classification"), "");
    let metadata = getMetadata(json, "metadata");
    let prompts = getPrompts(json, "prompts");
    return {
      TAG: "Ok",
      _0: {
        name: name,
        classification: classification,
        metadata: metadata,
        prompts: prompts
      }
    };
  } catch (raw_obj) {
    let obj = Primitive_exceptions.internalToException(raw_obj);
    if (obj.RE_EXN_ID === "JsExn") {
      let m = Stdlib_JsExn.message(obj._1);
      let msg = m !== undefined ? m : "Failed to parse manifest";
      return {
        TAG: "Error",
        _0: msg
      };
    }
    throw obj;
  }
}

function validate(manifest) {
  let errors = [];
  if (manifest.classification === "") {
    Js_array.push({
      field: "classification",
      message: "classification is required"
    }, errors);
  }
  let prompts = manifest.prompts;
  if (prompts !== undefined) {
    prompts.forEach(p => {
      if (p.name === "") {
        Js_array.push({
          field: "prompts.name",
          message: "prompt name cannot be empty"
        }, errors);
      }
      if (p.promptType === "Select" && p.options === undefined) {
        Js_array.push({
          field: "prompts.options",
          message: "select prompt requires options"
        }, errors);
        return;
      }
    });
  }
  if (errors.length === 0) {
    return {
      TAG: "Ok",
      _0: undefined
    };
  } else {
    return {
      TAG: "Error",
      _0: errors
    };
  }
}

export {
  parsePromptType,
  promptTypeToString,
  parse,
  validate,
}
/* yaml Not a pure module */
