---
to: config/<%= name %>-<%= environment %>.yaml
---
# <%= name %> configuration for <%= environment %> environment
# Generated by Fluxo - DO NOT EDIT MANUALLY

app:
  name: <%= name %>
  environment: <%= environment %>
  port: <%= port %>

database:
  host: <%= environment %>-db.example.com
  port: 5432
  name: <%= name %>_db
  pool_size: 10
  ssl_mode: <%= environment == "production" ? "require" : "disable" %>

cache:
  enabled: true
  ttl: 300
  max_entries: 1000

logging:
  level: <%= environment == "production" ? "warn" : "debug" %>
  format: json
  outputs:
    - type: stdout
      level: <%= environment == "production" ? "warn" : "info" %>
    - type: file
      level: debug
      path: logs/<%= name %>.log
      max_size: 100mb
      max_backups: 5

security:
  cors:
    enabled: true
    origins:
      - http://localhost:3000
      - https://<%= name %>.example.com
  rate_limit:
    enabled: <%= environment == "production" %>
    requests_per_minute: 60

features:
  analytics: <%= environment == "production" %>
  debug_mode: <%= environment == "development" %>
  maintenance_mode: false